/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATA_H_RPCGEN
#define _DATA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x123456
#define DATE_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define BIN_DATE 1
extern  long * bin_date_2(void *, CLIENT *);
extern  long * bin_date_2_svc(void *, struct svc_req *);
#define STR_DATE 2
extern  char ** str_date_2(long *, CLIENT *);
extern  char ** str_date_2_svc(long *, struct svc_req *);
extern int date_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BIN_DATE 1
extern  long * bin_date_2();
extern  long * bin_date_2_svc();
#define STR_DATE 2
extern  char ** str_date_2();
extern  char ** str_date_2_svc();
extern int date_prog_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATA_H_RPCGEN */
